import React from 'react'
import type { Metadata } from 'next'

import { Cairo } from 'next/font/google'
import './globals.css'

const cairo = Cairo({
  weight: ['300', '400', '600', '700', '900'],
  subsets: ['arabic'],
  variable: '--font-cairo',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ar">
      <body className={`${cairo.variable} antialiased`}>{children}</body>
    </html>
  )
}
